title: "Joel Hakavuori"
description: "PhD Student at Institut de mathématiques de Jussieu – Paris Rive Gauche (IMJ-PRG)"
url: "https://hakav.github.io"

theme: jekyll-theme-minimal

include:
  - _includes
